// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/ride-app/notification-service/repositories/token"
	"github.com/ride-app/notification-service/service"
	"github.com/ride-app/notification-service/third-party"
)

// Injectors from wire.go:

func InitializeService() (*service.NotificationServiceServer, error) {
	app, err := thirdparty.NewFirebaseApp()
	if err != nil {
		return nil, err
	}
	rtdbImpl, err := tokenrepository.NewRTDBTokenRepository(app)
	if err != nil {
		return nil, err
	}
	notificationServiceServer := service.New(rtdbImpl)
	return notificationServiceServer, nil
}
