name: Buf push

on:
  push:
    paths:
      - api/**
    branches:
      - main

jobs:
  buf-push:
    uses: ride-app/workflows/.github/workflows/buf-push.yaml@main
    with:
      buf-mod-dir: api
    secrets:
      buf-token: ${{ secrets.BUF_TOKEN }}
